http:
  hostname: ""
  port: 8000
  readTimeout: "5s"
  writeTimeout: "10s"
  idleTimeout: "2m"

app:
  name: "Goranchise"
  environment: "local"
  encryptionKey: "?E(G+KbPeShVmYq3t6w9z$C&F)J@McQf"

cache:
  hostname: "localhost"
  port: 6379
  password:
  maxAge:
    staticFile: 15552000
    page: 86400