http:
  hostname: ""
  port: 8000
  readTimeout: "5s"
  writeTimeout: "10s"
  idleTimeout: "2m"

app:
  name: "Goranchise"
  environment: "local"
  encryptionKey: "?E(G+KbPeShVmYq3t6w9z$C&F)J@McQf"
  timeout: "20s"

cache:
  hostname: "localhost"
  port: 6379
  password:
  expiration:
    staticFile: "4380h"
    page: "24h"

database:
  hostname: "127.0.0.1"
  port: 5432
  user: "admin"
  password: "admin"
  database: "goranchise"