http:
  hostname: ""
  port: 8000
  readTimeout: "5s"
  writeTimeout: "10s"
  idleTimeout: "2m"
  tls:
    enabled: false
    certificate: ""
    key: ""

app:
  name: "Goranchise"
  environment: "local"
  encryptionKey: "?E(G+KbPeShVmYq3t6w9z$C&F)J@McQf"
  timeout: "20s"
  passwordToken:
    expiration: 60m
    length: 64

cache:
  hostname: "localhost"
  port: 6379
  password:
  expiration:
    staticFile: "4380h"
    page: "24h"

database:
  hostname: "127.0.0.1"
  port: 5432
  user: "admin"
  password: "admin"
  database: "goranchise"
  testDatabase: "goranchise_test"

mail:
  hostname: localhost
  port: 25
  user: admin
  password: admin
  fromAddress: admin@localhost